# Database configuration
spring:
  datasource:
    url: ${SUPABASE_DATABASE_URL}
    username: ${SUPABASE_DATABASE_USERNAME}
    password: ${SUPABASE_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

# Server configuration
server:
  port: 8443
  tomcat:
    max-part-count: 20
  ssl:
    enabled: true
    key-store: classpath:ssl/localhost.p12
    key-store-type: PKCS12
    key-store-password: ${PKCS12_STORE_PASSWORD}
    key-alias: localhost
  servlet:
    context-path: /candle-shop-project-api

# Supabase configuration
supabase:
  secret:
    service-role-key: ${SUPABASE_SERVICE_ROLE_KEY}
  storage:
    public-image-base-url: ${SUPABASE_PUBLIC_STORAGE_URL}
    base-url: ${SUPABASE_STORAGE_BASE_URL}
  expiration:
    seller:
      check-qr-payment: ${SUPABASE_SELLER_CHECK_QR_PAYMENT_EXP}
      check-receipt: ${SUPABASE_SELLER_CHECK_RECEIPT_EXP}
    customer:
      check-qr-payment: ${SUPABASE_USER_CHECK_QR_PAYMENT_EXP}

