# Application configuration
app:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}

spring:
  application:
    name: candle-shop-project
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url : ${SUPABASE_DATABASE_URL}
    username: ${SUPABASE_DATABASE_USERNAME}
    password: ${SUPABASE_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming.physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
  jackson:
    property-naming-strategy: SNAKE_CASE


# Logging configuration
logging:
  level:
    app: DEBUG
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SXXX}|%level|${spring.application.name}|${PID}|%thread|%logger{40}|%message%n"

#Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

# Supabase configuration
supabase:
  secret:
    service-role-key: ${SUPABASE_SERVICE_ROLE_KEY}
  storage:
    public-image-base-url: ${SUPABASE_PUBLIC_STORAGE_URL}
    base-url: ${SUPABASE_STORAGE_BASE_URL}
  expiration:
    seller:
      check-qr-payment: ${SUPABASE_SELLER_CHECK_QR_PAYMENT_EXP}
      check-reciept: ${SUPABASE_SELLER_CHECK_RECEIPT_EXP}
    customer:
      check-qr-payment: ${SUPABASE_USER_CHECK_QR_PAYMENT_EXP}
