spring.application.name=candle-shop-project

spring.datasource.url=jdbc:postgresql://db.goerhyygukxfkphuyrnw.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=LLspUvDx867DJ_x

# Database configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging configuration
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE

#Swagger configuration
springdoc.swagger-ui.path=/candle-shop-project/swagger-ui.html